coverage:
    status:
        # coverage of the current PR/commit
        patch:
            default:
                target: auto
        # coverage of the full project
        project:
            tests: 
                target: auto
comment: false