version: 2

sphinx:
   configuration: doc/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
   install:
    - method: pip
      path: .
      extra_requirements:
        - docs