version: 2

sphinx:
   configuration: docs/conf.py
   fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
   install:
    - method: pip
      path: .
      extra_requirements:
        - docs
