name: tmp

# A temporary workflow that only tests the releasing.
# This is useful to make sure that the CD picks up the changes.

on:
  pull_request:
    branches: [ master ]

jobs:
  initial_check:
    name: Should release?
    if: github.repository_owner == 'imageio'
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.skippy.outputs.release }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        pip install python-semantic-release
    - name: skippy
      id: skippy
      run: |
        if [[ $(semantic-release print-version 2>/dev/null) = "" ]]; then
          echo "::set-output name=release::false"
          echo "No changes to the API detected."
          echo "Workdir: $PWD"
          semantic-release -v DEBUG print-version
          git status
        else
          echo "::set-output name=release::true"
          echo "Workdir: $PWD"
          echo "Releasing v$(semantic-release print-version)"
        fi
    - name: Skipping Release
      if: ${{ steps.skippy.outputs.release == 'false' }}
      run: echo ${{ steps.skippy.outputs.release }}
    - name: Releasing New Version
      if: ${{ steps.skippy.outputs.release == 'true' }}
      run: echo ${{ steps.skippy.outputs.release }}